### ISSUE TITLE
Can't get R packages to install in the install

### ISSUE THREAD

**Issue by steventroysimpson** [nsh87/shinyVM#5]
How can I get the disk space I need to install new packages?  quite frustrating

**Comment by nsh87** [comment]
Good point...I'll put something in the README. Open up *Vagrantfile*, the settings for the VM are in there, which you can change. Right now there is "1536" RAM (~1.5GB). You can change the value and then do `vagrant reload`.

**Comment by steventroysimpson** [comment]
I bump it up to 5GB in Vagrantfile.

After I `vagrant up` again and `vagrant ssh`, I `sudo R` and try a simple install: `install.packages("devtools")` and I get the following errors

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘httr’, ‘RCurl’

"trying URL 'http://lib.stat.cmu.edu/R/CRAN/src/contrib/httr_0.6.1.tar.gz'
Content type 'application/x-gzip' length 247531 bytes (241 KB)
opened URL
downloaded 241 KB

trying URL 'http://lib.stat.cmu.edu/R/CRAN/src/contrib/RCurl_1.95-4.5.tar.gz'
Content type 'application/x-gzip' length 878607 bytes (858 KB)
opened URL
downloaded 858 KB

trying URL 'http://lib.stat.cmu.edu/R/CRAN/src/contrib/devtools_1.7.0.tar.gz'
Content type 'application/x-gzip' length 130760 bytes (127 KB)
opened URL
downloaded 127 KB

* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ successfully unpacked and MD5 sums checked
checking for curl-config... no
Cannot find curl-config
ERROR: configuration failed for package ‘RCurl’
* removing ‘/usr/local/lib/R/site-library/RCurl’
ERROR: dependency ‘RCurl’ is not available for package ‘httr’
* removing ‘/usr/local/lib/R/site-library/httr’
ERROR: dependencies ‘httr’, ‘RCurl’ are not available for package ‘devtools’
* removing ‘/usr/local/lib/R/site-library/devtools’

The downloaded source packages are in
	‘/tmp/RtmpvSClWS/downloaded_packages’
Warning messages:
1: In install.packages("devtools") :
  installation of package ‘RCurl’ had non-zero exit status
2: In install.packages("devtools") :
  installation of package ‘httr’ had non-zero exit status
3: In install.packages("devtools") :
  installation of package ‘devtools’ had non-zero exit status
> "

**Comment by steventroysimpson** [comment]
how do I get to `/tmp/RtmpvSClWS/downloaded_packages` to do a R CMD INSTALL?

**Comment by steventroysimpson** [comment]
I bumped it up to 20GB and it still is getting this error on RCurl and devtools. I tried the scales package and it installed ok. But I need devtools to get some github packages installed.

**Comment by steventroysimpson** [comment]
This Stackoverflow answer solved the problem. Need to include curl and xml in the ubuntu install for R to load packages RCurl and XML

http://stackoverflow.com/questions/20671814/non-zero-exit-status-r-3-0-1-xml-and-rcurl

**Comment by nsh87** [comment]
Ah, yes, RCurl has some dependencies outside of R. I added that to the Readme this morning, a moment too late it seems.
