### ISSUE TITLE
`Shared folders

### ISSUE THREAD

**Issue by fedenolasco** [nsh87/shinyVM#6]
Hi Nikhil,

I have a local D: drive syncing to onedrive where my ShinyVM folder resides. vagrant does mount the shared folders in the VM and I cannot seem to find where the issue is. Best regards, Fede.

![2016-03-03_2310](https://cloud.githubusercontent.com/assets/15969594/13512887/595802fc-e195-11e5-8565-457c16ed0ae1.png)

**Comment by nsh87** [comment]
@fedenolasco: I assume you meant Vagrant _doesn't_ mount the shared folders, not "vagrant does mount the shared folders"? Can you sent the output of `vagrant up`?

**Comment by fedenolasco** [comment]
Hi Nikhil,

Correct, the shared folders are not mounted. If you look at the path in the screen capture there is a ? mark. I am not myself to familiar with linux.

Here is the output of  vagrant up

`D:\onedrive\Documents\vm\shinyVM>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You curr
ently
==> default: have version '20160224.0.0'. The latest is version '20160301.0.0'.
Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3838 (guest) => 7070 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version o
f
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you
 see
    default: shared folder errors, please make sure the guest additions within t
he
    default: virtual machine match the version of VirtualBox you have installed
on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/onedrive/Documents/vm/shinyVM
    default: /www-shiny => D:/onedrive/Documents/vm/shinyVM/project
    default: /writeable-project => D:/onedrive/Documents/vm/shinyVM/writeable-pr
oject
==> default: Machine already provisioned. Run `vagrant provision` or use the `--
provision`
==> default: flag to force provisioning. Provisioners marked to run always will
still run.

D:\onedrive\Documents\vm\shinyVM>vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You curr
ently
==> default: have version '20160224.0.0'. The latest is version '20160301.0.0'.
Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3838 (guest) => 7070 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version o
f
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you
 see
    default: shared folder errors, please make sure the guest additions within t
he
    default: virtual machine match the version of VirtualBox you have installed
on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/onedrive/Documents/vm/shinyVM
    default: /www-shiny => D:/onedrive/Documents/vm/shinyVM/project
    default: /writeable-project => D:/onedrive/Documents/vm/shinyVM/writeable-pr
oject
==> default: Machine already provisioned. Run `vagrant provision` or use the `--
provision`
==> default: flag to force provisioning. Provisioners marked to run always will
still run.

D:\onedrive\Documents\vm\shinyVM>vagrant halt
==> default: Attempting graceful shutdown of VM...

D:\onedrive\Documents\vm\shinyVM>vagrant reload
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You curr
ently
==> default: have version '20160224.0.0'. The latest is version '20160301.0.0'.
Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 3838 (guest) => 7070 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version o
f
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you
 see
    default: shared folder errors, please make sure the guest additions within t
he
    default: virtual machine match the version of VirtualBox you have installed
on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/onedrive/Documents/vm/shinyVM
    default: /www-shiny => D:/onedrive/Documents/vm/shinyVM/project
    default: /writeable-project => D:/onedrive/Documents/vm/shinyVM/writeable-pr
oject
==> default: Machine already provisioned. Run `vagrant provision` or use the `--
provision`
==> default: flag to force provisioning. Provisioners marked to run always will
still run.

D:\onedrive\Documents\vm\shinyVM>

`

**Comment by nsh87** [comment]
@fedenolasco, is your VirtualBox up to date? You can try installing the [vagrant-vbguest](http://kvz.io/blog/2013/01/16/vagrant-tip-keep-virtualbox-guest-additions-in-sync/) plugin. The message indicates this about shared folders:

```
==> default: Checking for guest additions in VM...
default: The guest additions on this VM do not match the installed version of
default: VirtualBox! In most cases this is fine, but in rare cases it can
default: prevent things such as shared folders from working properly. If you see
default: shared folder errors, please make sure the guest additions within the
default: virtual machine match the version of VirtualBox you have installed on
default: your host and reload your VM.
default:
default: Guest Additions Version: 4.3.36
default: VirtualBox Version: 5.0
```

**Comment by nsh87** [comment]
@fedenolasco, were you able to resolve this?
